name: Get PM2 Logs
on: [push]
jobs:
  logs:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Logs
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 22
          script: |
            cd /home/${{ secrets.SERVER_USER }}/htdocs/crm.populatia.ro
            npx pm2 logs --lines 1000 --err --nostream > public/pm2_err.txt || pm2 logs --lines 1000 --err --nostream > public/pm2_err.txt || true
            npx pm2 logs --lines 1000 --nostream > public/pm2_out.txt || pm2 logs --lines 1000 --nostream > public/pm2_out.txt || true
